###
POST http://localhost:4000/api/auth/generate-otp?mode=signup
Content-Type: application/json

{
  "email": "consumer@gmail.com"
}

###
POST http://localhost:4000/api/auth/generate-otp
Content-Type: application/json

{
  "email": "lawyer9@gmail.com"
}

###
POST http://localhost:4000/api/auth/generate-otp
Content-Type: application/json

{
  "email": "student@gmail.com"
}

###
POST http://localhost:4000/api/auth/verify-signup-otp
Content-Type: application/json

{
  "email": "consumer12@gmail.com",
  "otp": 1234,
  "name": "consumer",
  "role": "consumer",
  "password": "password123"
}

###
POST http://localhost:4000/api/auth/verify-signup-otp
Content-Type: application/json

{
  "email": "lawyer97@gmail.com",
  "otp": 1234,
  "name": "lawyer8",
  "role": "lawyer",
  "password": "password123"
}

###
POST http://localhost:4000/api/auth/verify-signup-otp
Content-Type: application/json

{
  "email": "student19@gmail.com",
  "otp": 1234,
  "name": "student",
  "role": "student",
  "password": "password123"
}
