### 

POST http://localhost:4000/api/auth/generate-otp?mode=signup HTTP/1.1
Content-Type: application/json

{
  "email": "consumer@gmail.com"
}


### 

POST http://localhost:4000/api/auth/generate-otp HTTP/1.1
Content-Type: application/json

{
  "email": "lawyer@gmail.com"
}


### 

POST http://localhost:4000/api/auth/generate-otp HTTP/1.1
Content-Type: application/json

{
  "email": "student@gmail.com"
}


### 

POST http://localhost:4000/api/auth/verify-signup-otp HTTP/1.1
Content-Type: application/json

{
  "email": "consumer@gmail.com",
  "name": "consumer",
  "otp": 1234,
  "password": "password123",
  "role": "consumer"
}


### 

POST http://localhost:4000/api/auth/verify-signup-otp HTTP/1.1
Content-Type: application/json

{
  "email": "lawyer@gmail.com",
  "name": "lawyer",
  "otp": 1234,
  "password": "password123",
  "role": "lawyer"
}


### 

POST http://localhost:4000/api/auth/verify-signup-otp HTTP/1.1
Content-Type: application/json

{
  "email": "student19@gmail.com",
  "name": "student",
  "otp": 1234,
  "password": "password123",
  "role": "student"
}
