### ------ WEB SOCKETS ------ ###

WEBSOCKET ws://localhost:4001/chat?to=399257256345&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mzk5MjU3MjU2MzQ1LCJyb2xlIjoiY29uc3VtZXIiLCJpc19wcm9maWxlX2NvbXBsZXRlIjp0cnVlLCJpYXQiOjE3NTcxNDE3ODMsImV4cCI6MTc1NzIyODE4M30.1epzDaefDqPmy9nfmeRmrrMdwDlsu5LoiZ_q-imENwk 
Cookie: sessionId=abc123

{
  "message": "hi from consumer meant for lawyer"
}


### 

GET WS ws://localhost:4001/chat?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJfMTc1MDE2MjExNzUzNTlobjIiLCJyb2xlIjoibGF3eWVyIiwiaWF0IjoxNzUwMzM5NDU4LCJleHAiOjE3NTAzNDMwNTh9.jpWxcuZ1ja-clPLR_eQItIeYUHX9J42pAk5v27nccdk HTTP/1.1

{
  "content": "hi from lawyer",
  "from": "user_23323",
  "to": "user_99999"
}


### 

GET WS ws://localhost:4001/chat?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJfMTc1MDE2MTA3NTgzOGx0NW8iLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc1MDMzOTY4NSwiZXhwIjoxNzUwMzQzMjg1fQ.SsSgUKaqXW9FVp2drBuJAmqFbpYWaXR62qeePDpnkzw HTTP/1.1

{
  "content": "hi from lawyer",
  "from": "user_23323",
  "to": "user_99999"
}
